## SVM on cancer data

sklearn.svm.SVC (C=1.0, kernel= ‘rbf’, degree=3)

C parameter : Keeping large values of C will indicate the SVM model to choose a smaller margin hyperplane. 
   
              Small value of C will indicate the SVM model to choose a larger margin hyperplane.

kernel parameter : It is the kernel type to be used in SVM model building. 
       
                   It can be ‘linear’, ‘rbf’, ‘poly’, or ‘sigmoid’. The default value of kernel is ‘rbf’.

degree parameter : It’s only considered in the case of polynomial kernel. 
      
                   It is the degree of the polynomial kernel function. The default value of degree is 3.
        
Gamma parameter :  Gamma decides that how much curvature we want in a decision boundary.

                   Gamma high means more curvature.

                   Gamma low means less curvature.

In [12]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix

In [13]:

df = pd.read_csv("cancer.csv")

In [14]:

df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [15]:

# Convert diagnosis M/B → 1/0
df["diagnosis"] = df["diagnosis"].map({"M": 1, "B": 0})

In [16]:
# Drop id column

df = df.drop("id", axis=1)

In [17]:

# Split features and label
X = df.drop("diagnosis", axis=1)

y = df["diagnosis"]

In [18]:
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [19]:

# TRAIN / TEST SPLIT

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=109
)

In [20]:
# Scale features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
# SVM – Linear

clf_linear = SVC(kernel='linear')
clf_linear.fit(X_train, y_train)
pred_linear = clf_linear.predict(X_test)

print("\n=== Linear Kernel ===")
print("Accuracy:", accuracy_score(y_test, pred_linear))
print("Precision:", precision_score(y_test, pred_linear))
print("Recall:", recall_score(y_test, pred_linear))
print(confusion_matrix(y_test, pred_linear))
print(classification_report(y_test, pred_linear))

=== Linear Kernel ===
Accuracy: 0.9883040935672515
Precision: 1.0
Recall: 0.9682539682539683
[[108   0]
 [  2  61]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       108
           1       1.00      0.97      0.98        63

    accuracy                           0.99       171
   macro avg       0.99      0.98      0.99       171
weighted avg       0.99      0.99      0.99       171

In [22]:

# SVM – Polynomial

clf_poly = SVC(kernel='poly')
clf_poly.fit(X_train, y_train)
pred_poly = clf_poly.predict(X_test)

print("\n=== Polynomial Kernel ===")
print("Accuracy:", accuracy_score(y_test, pred_poly))
print("Precision:", precision_score(y_test, pred_poly))
print("Recall:", recall_score(y_test, pred_poly))

=== Polynomial Kernel ===
Accuracy: 0.9005847953216374
Precision: 1.0
Recall: 0.7301587301587301

In [23]:

# -------------------------------
# SVM – RBF
# -------------------------------
clf_rbf = SVC(kernel='rbf')
clf_rbf.fit(X_train, y_train)
pred_rbf = clf_rbf.predict(X_test)

print("=== RBF Kernel ===")
print("Accuracy:", accuracy_score(y_test, pred_rbf))

=== RBF Kernel ===
Accuracy: 0.9824561403508771

In [24]:

# SVM – Sigmoid

clf_sig = SVC(kernel='sigmoid')
clf_sig.fit(X_train, y_train)
pred_sig = clf_sig.predict(X_test)

print("\n=== Sigmoid Kernel ===")
print("Accuracy:", accuracy_score(y_test, pred_sig))

=== Sigmoid Kernel ===
Accuracy: 0.9707602339181286

In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    classification_report, confusion_matrix
)
from sklearn.preprocessing import StandardScaler


df = pd.read_csv("cancer.csv")


# Convert diagnosis M/B → 1/0
df["diagnosis"] = df["diagnosis"].map({"M": 1, "B": 0})

# Drop id column
df = df.drop("id", axis=1)

# Split features and label
X = df.drop("diagnosis", axis=1)
y = df["diagnosis"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=109
)

# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


def evaluate_model(name, y_true, y_pred):
    print(f"\n===== {name} Kernel =====")
    print("Accuracy :", accuracy_score(y_true, y_pred))
    print("Precision:", precision_score(y_true, y_pred))
    print("Recall   :", recall_score(y_true, y_pred))
    print("\nConfusion Matrix:\n", confusion_matrix(y_true, y_pred))
    print("\nClassification Report:\n", classification_report(y_true, y_pred))


# ---------------------------------------------
# SVM – Linear
# ---------------------------------------------
clf_linear = SVC(kernel='linear')
clf_linear.fit(X_train, y_train)
pred_linear = clf_linear.predict(X_test)
evaluate_model("Linear", y_test, pred_linear)


# ---------------------------------------------
# SVM – Polynomial
# ---------------------------------------------
clf_poly = SVC(kernel='poly', degree=3)  # degree can be tuned
clf_poly.fit(X_train, y_train)
pred_poly = clf_poly.predict(X_test)
evaluate_model("Polynomial", y_test, pred_poly)


# ---------------------------------------------
# SVM – RBF
# ---------------------------------------------
clf_rbf = SVC(kernel='rbf')
clf_rbf.fit(X_train, y_train)
pred_rbf = clf_rbf.predict(X_test)
evaluate_model("RBF", y_test, pred_rbf)


# ---------------------------------------------
# SVM – Sigmoid
# ---------------------------------------------
clf_sig = SVC(kernel='sigmoid')
clf_sig.fit(X_train, y_train)
pred_sig = clf_sig.predict(X_test)
evaluate_model("Sigmoid", y_test, pred_sig)

===== Linear Kernel =====
Accuracy : 0.9883040935672515
Precision: 1.0
Recall   : 0.9682539682539683

Confusion Matrix:
 [[108   0]
 [  2  61]]

Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       108
           1       1.00      0.97      0.98        63

    accuracy                           0.99       171
   macro avg       0.99      0.98      0.99       171
weighted avg       0.99      0.99      0.99       171


===== Polynomial Kernel =====
Accuracy : 0.9005847953216374
Precision: 1.0
Recall   : 0.7301587301587301

Confusion Matrix:
 [[108   0]
 [ 17  46]]

Classification Report:
               precision    recall  f1-score   support

           0       0.86      1.00      0.93       108
           1       1.00      0.73      0.84        63

    accuracy                           0.90       171
   macro avg       0.93      0.87      0.89       171
weighted avg       0.91      0.90      0.90       171


===== RBF Kernel =====
Accuracy : 0.9824561403508771
Precision: 1.0
Recall   : 0.9523809523809523

Confusion Matrix:
 [[108   0]
 [  3  60]]

Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.99       108
           1       1.00      0.95      0.98        63

    accuracy                           0.98       171
   macro avg       0.99      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171


===== Sigmoid Kernel =====
Accuracy : 0.9707602339181286
Precision: 0.967741935483871
Recall   : 0.9523809523809523

Confusion Matrix:
 [[106   2]
 [  3  60]]

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.98      0.98       108
           1       0.97      0.95      0.96        63

    accuracy                           0.97       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171